### ISSUE TITLE
Enhancement Suggestion ..

### ISSUE THREAD

**Issue by ack72tdp** [pravega/pravega-benchmark#3]
Current tool operation is tightly coupled with segments/producers/number of threads .. As an enhancement we probably want to decouple them .. and have flexibility to vary them using command line options..

**Comment by arvindkandhare** [comment]
@ack72tdp can you explain in more detail the scenario that you are trying to exercise? While having these vary can be good, ideally the perf should be independent of these.

**Comment by kmgowda** [comment]
This PR : https://github.com/pravega/pravega-benchmark/pull/9
has this above enhancement implemented

**Comment by kmgowda** [comment]
the latest changes this : https://github.com/pravega/pravega-benchmark/pull/11 has this feature

**Comment by RaulGracia** [comment]
Closed via #11.
