### ISSUE TITLE
Reads doesn't work with tool 

### ISSUE THREAD

**Issue by ack72tdp** [pravega/pravega-benchmark#4]
Reads doesn't work with tool .. 

[root@white-master-3 pravega-benchmark]# bin/pravega-benchmark  -controller tcp://10.240.135.50:9091 --stream consumertest  --consumers 10  --randomkey true --writeonly false --size 1000 --eventspersec 30000 --runtime 120
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.240.135.50:9091
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[addrs=[/10.240.135.50:9091], attrs={}]]
[grpc-default-executor-0] WARN io.pravega.client.stream.impl.ControllerImpl - Scope already exists: Scope
[main] INFO io.pravega.client.admin.impl.StreamManagerImpl - Creating scope/stream: Scope/consumertest with configuration: StreamConfiguration(scope=Scope, streamName=consumertest, scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=20), retentionPolicy=null)
[grpc-default-executor-1] WARN io.pravega.client.stream.impl.ControllerImpl - Stream already exists: consumertest
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.240.135.50:9091
[main] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Shutting down ControllerNameResolver
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.240.135.50:9091
Exception in thread "main" java.lang.IllegalArgumentException: Stream names that the reader group can read from cannot be empty
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at io.pravega.client.stream.ReaderGroupConfig$ReaderGroupConfigBuilder.build(ReaderGroupConfig.java:38)
        at com.emc.pravega.perf.PravegaPerfTest.main(PravegaPerfTest.java:121)

**Comment by RaulGracia** [comment]
Readers are working now. Please, re-open the issue if you can reproduce it.
