### ISSUE TITLE
Need a command parameter to create or not to create scope

### ISSUE THREAD

**Issue by dandaoatdell** [pravega/pravega-benchmark#52]
In certain environment, the scope is already created. So there's no need for PB to create the scope.
This is what is currently in PravegaStreamHandler.java 

 67         this.bgexecutor = bgexecutor;
 68         streamManager = StreamManager.create(new URI(uri));
 69         streamManager.createScope(scope);
 70         streamconfig = StreamConfiguration.builder().scope(scope).streamName(stream)

the scope is created at line 69.

I'd like to propose an additional command parameter i.e. '-create-scope false ' to by pass the scope creation.
For backward comparability the default should be true.

**Comment by claudiofahey** [comment]
PR #68 submitted.

**Comment by maddisondavid** [comment]
PR for this opened here #93
