### ISSUE TITLE
Need a command parameter to not altering stream create or scaling

### ISSUE THREAD

**Issue by dandaoatdell** [pravega/pravega-benchmark#53]
In some environment, there's no need for PB to scale the stream, i.e. these are the current code from PravegaPerfTest.java

405
406             if (producerCount > 0 && !streamHandle.create()) {
407                 if (recreate) {
408                     streamHandle.recreate();
409                 } else {
410                     streamHandle.scale();
411                 }
412             }

Propose to have a command parameter to by pass this section i.e. -stream-scale false

**Comment by RaulGracia** [comment]
This has been addressed in #93.
