### ISSUE TITLE
Enable Nautilus-compatible build

### ISSUE THREAD

**Issue by claudiofahey** [pravega/pravega-benchmark#73]
Add the ability to include the Nautilus authentication library by turning on a flag in gradle.properties. By default, the Nautilus authentication library will not be included.

**Comment by maddisondavid** [comment]
I think it's fine to include the pravega-keycloak JAR as a runtime dependency in this project.  If the specific environment variables are not set then the inclusion of the JAR is benign.  This will allow the benchmark to run in secure and unsecure environments with no changes.   

**References:**
- https://github.com/pravega/pravega-keycloak
