### ISSUE TITLE
pravega-benchmark issues

### ISSUE THREAD

**Issue by sanjaynv** [pravega/pravega-benchmark#82]
HI, I am new to this pravega, I received an error while executing the following command line
$ pravega-benchmark/bin/pravega-benchmark -controller tcp://127.0.0.1:9090 -stream streamname1 -segments 1 -producers 1 -size 100 -throughput -1 -time 60
  
I got an error

 like this
2019-11-27 12:20:49:670 +0530 [grpc-default-executor-1] WARN io.pravega.client.stream.impl.ControllerImpl - gRPC call for createScope with trace id -5079440618826258426 failed with server error.
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception

can anyone pls sort out this problem

**Comment by RaulGracia** [comment]
Hi @sanjaynv, if you see this `UNAVAILABLE` means that the Pravega Controller is not working or reachable. Have you started a Pravega cluster in the first place? If so, is the Pravega Controller running at `127.0.0.1`?

**Comment by sanjaynv** [comment]
Thanks.... ur information is very helpfull.
